kind: pipeline
type: docker
name: webkit-screenshot

# 自定义工作区
workspace:
  path: /drone/src

steps:

- name: restore-cache # 把之前缓存好的数据取出
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount: # 缓存挂载的文件夹
      - ./golang-cache
  volumes:
    - name: cache
      path: /cache

- name: build
  image: therecipe/qt:linux_fedora
  commands:
    # 恢复缓存目录
    - go env -w GOPROXY=https://goproxy.cn,direct
    - mkdir -p ./golang-cache
    - cd ./golang-cache && mkdir -p github.com && cp -r * ~/work/src/ && cd ..
    # 构建
    - git config --global http.proxy 'socks5://10.20.56.78:10808'
    - git config --global https.proxy 'socks5://10.20.56.78:10808'
    - go get -d -v github.com/OneOfOne/xxhash
    - go get -d -v github.com/corona10/goimagehash
    - go get -d -v gorm.io/gorm
    - go get -d -v gorm.io/driver/sqlite
    - mkdir -p ~/work/src/github.com/akkuman/webkit-screenshot
    - pwd
    - cp -r * ~/work/src/github.com/akkuman/webkit-screenshot/
    - cd ~/work/src/github.com/akkuman/webkit-screenshot
    - pwd
    - ls
    - bash -c "QT_WEBKIT=true qtdeploy build linux main.go"
    - tar zcvPf /drone/src/webkit-screenshot.tar.gz ~/work/src/github.com/akkuman/webkit-screenshot/deploy
    - cd /drone/src
    - pwd
    # 创建缓存目录
    - cp -r ~/work/src/* ./golang-cache/

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: http://git.ah-strategy.online
    files: /drone/src/webkit-screenshot.tar.gz
    title: webkit-screenshot
  when:
    event: tag

- name: rebuild-cache # 把依赖和 npm 缓存放到缓存里
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ./golang-cache
  volumes:
    - name: cache
      path: /cache

- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token: 
      from_secret: dingtalk_token
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true

# 声明并挂载缓存文件夹，宿主机的路径为 /tmp/cache，需要设置 Project settings 为 Trusted
volumes:
- name: cache
  host:
    path: /tmp/cache